### ISSUE TITLE
TypeError: eq() received an invalid combination of arguments

### ISSUE THREAD

**Issue by DonaldKam** [YihongSun/Bayesian-Amodal#2]
Another issue arose:

Dim Reduction - aeroplane: (28, 64) --> (18, 54)
Dim Reduction - bicycle: (36, 37) --> (30, 31)
Dim Reduction - boat: (65, 153) --> (49, 101)
Dim Reduction - bottle: (89, 57) --> (63, 41)
Dim Reduction - bus: (31, 61) --> (25, 45)
Dim Reduction - car: (27, 69) --> (19, 47)
Dim Reduction - chair: (38, 25) --> (30, 19)
Dim Reduction - diningtable: (25, 86) --> (19, 50)
Dim Reduction - motorbike: (41, 38) --> (31, 28)
Dim Reduction - sofa: (21, 55) --> (19, 35)
Dim Reduction - train: (55, 187) --> (29, 109)
Dim Reduction - tvmonitor: (45, 36) --> (25, 30)
Loaded Pretrain Model: ../Models/E2E/pascal_final.pth
Traceback (most recent call last):
  File "run_experiment.py", line 376, in <module>
    net.update_fused_models(omega=omega)
  File "/home/university/Downloads/BAS/Code/Net.py", line 905, in update_fused_models
    if fg_model == None:
TypeError: eq() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (Number other)
      didn't match because some of the arguments have invalid types: (NoneType)

**Comment by YihongSun** [comment]
try `if fg_model is None:`
