### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'gt_alignment'

### ISSUE THREAD

**Issue by DonaldKam** [YihongSun/Bayesian-Amodal#4]
I am using Pytorch 1.13.1. It seems that it does not support the argument 'gt_alignment'. However, gt_alignment seems important in your codes. How should I address this problem?

Dim Reduction - aeroplane: (28, 64) --> (18, 54)
Dim Reduction - bicycle: (36, 37) --> (30, 31)
Dim Reduction - boat: (65, 153) --> (49, 101)
Dim Reduction - bottle: (89, 57) --> (63, 41)
Dim Reduction - bus: (31, 61) --> (25, 45)
Dim Reduction - car: (27, 69) --> (19, 47)
Dim Reduction - chair: (38, 25) --> (30, 19)
Dim Reduction - diningtable: (25, 86) --> (19, 50)
Dim Reduction - motorbike: (41, 38) --> (31, 28)
Dim Reduction - sofa: (21, 55) --> (19, 35)
Dim Reduction - train: (55, 187) --> (29, 109)
Dim Reduction - tvmonitor: (45, 36) --> (25, 30)

Training Tag: 11_7_align_1g
Training...
Traceback (most recent call last):
  File "train_CompNet.py", line 350, in <module>
    train(model=net, train_loader=train_loader, test_loader=test_loader, epochs=epochs, batch_size=batch_size, learning_rate=lr, savedir=checkpoint_dir, alpha=alpha, beta=beta, gamma=gamma, vc_flag=vc_flag, mix_flag=mix_flag, prior_flag=prior_flag)
  File "train_CompNet.py", line 165, in train
    acc, meanIoU = eval(model, test_loader, header='Initial Eval')
  File "train_CompNet.py", line 96, in eval
    pred_scores, pred_confidence, pred_amodal_bboxes, pred_segmentations = model(org_x=input, bboxes=input_bbox, bbox_type=input_bbox_type, input_label=None, mask_label_training=gt_labels[0].numpy(), gt_alignment=input_alighnments)
  File "/home/ru/anaconda3/envs/amodal/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'gt_alignment'

**Comment by DonaldKam** [comment]
It may be a very serious academic cheating event if you don't answer the question above as I can not reproduce the results, nor can I cite a cheating paper.

**Comment by YihongSun** [comment]
#1
