### ISSUE TITLE
NameError: name 'sub_tag' is not defined

### ISSUE THREAD

**Issue by DonaldKam** [YihongSun/Bayesian-Amodal#5]
'sub_tag' is used in 'eval_performance'. However, this variable is not pre-defined in 'eval_performance'.

**The error is:**
File "run_experiment.py", line 295, in eval_performance
    out_dir = demo_dir + '{}/'.format(sub_tag)
NameError: name 'sub_tag' is not defined

**The code is:**
def eval_performance(data_loader, rpn_results, demo=False, category='car', eval_modes=('inmodal', 'amodal'), input_bbox_type='inmodal', input_gt_label=True, search_for_file=True):
    N = data_loader.__len__()

    cls_acc = []
    amodal_bbox_iou = []
    amodal_height = []
    occ = []
    disp_iou, disp_counter = 0, 0

    mask_dict = dict()
    for eval in eval_modes:
        mask_dict[eval] = {'img_index': [], 'obj_index': [], 'iou': [], 'bmask_thrd': binary_mask_thrds[eval]}

    input_bbox = None
    input_label = None
    gt_seg = None
    RPN_PREDICTION = []

    for ii, data in enumerate(data_loader):

        input_tensor, gt_labels, gt_inmodal_bbox, gt_amodal_bbox, gt_inmodal_segmentation, gt_amodal_segmentation, gt_occ, demo_img, img_path, failed = data
        if failed.item():
            continue

        gt_labels, gt_occ = gt_labels[0].numpy(), gt_occ[0].numpy()
        gt_inmodal_bbox, gt_amodal_bbox = gt_inmodal_bbox[0], gt_amodal_bbox[0]
        gt_inmodal_segmentation, gt_amodal_segmentation = gt_inmodal_segmentation[0].numpy(), gt_amodal_segmentation[0].numpy()

        if input_bbox_type == 'inmodal':
            input_bbox = copy.deepcopy(gt_inmodal_bbox)
        elif input_bbox_type == 'amodal':
            input_bbox = copy.deepcopy(gt_amodal_bbox)

        if input_gt_label:
            input_label = gt_labels.copy()

        bad_bbox = False
        for bi, box in enumerate(input_bbox):
            if box[2] - box[0] == 0 or box[3] - box[1] == 0:
                bad_bbox = True
                break
        if bad_bbox:
            continue

        if TABLE_NUM == 1 or TABLE_NUM == 2:
            load_ii = ii
            if search_for_file:
                for load_ii in range(len(rpn_results)):
                    if same_filename(rpn_results[load_ii]['file_name'], img_path[0]): 
                        break
            else:
                if not same_filename(rpn_results[load_ii]['file_name'], img_path[0]):
                    print('error, skip')
                    continue
            
            rpn_input_box = []
            for box in input_bbox:
                box, iou = find_max_iou(rpn_results[load_ii]['bbox'], box.cpu().numpy())
                RPN_PREDICTION.append(iou)
                rpn_input_box.append(box.astype(int))
        elif TABLE_NUM == 3:
            rpn_input_box = []
            for box in input_bbox:
                img_name_sep = str(img_path[0]).split('/')
                img_name = '/home/r0935223/Downloads/BAS/Dataset/COCO/' + '/'.join(img_name_sep[-2:]) 
                box, iou = find_max_iou(rpn_results[img_name]['bbox'], box.cpu().numpy())
                RPN_PREDICTION.append(iou)
                rpn_input_box.append(box.astype(int))

        rpn_input_box = torch.tensor(np.stack(rpn_input_box))

        
        with torch.no_grad():
            pred_scores, pred_confidence, pred_amodal_bboxes, pred_segmentations = net(org_x=input_tensor.cuda(device_ids[0]), bboxes=rpn_input_box, bbox_type=input_bbox_type, input_label=input_label)

        pred_acc = (gt_labels == pred_scores.argmax(1).cpu().numpy()).astype(float)

        for obj_idx in range(len(pred_amodal_bboxes)):

            pred_segmentation = pred_segmentations[obj_idx]

            if np.sum(gt_inmodal_segmentation[obj_idx]) == 0:
                continue

            for mask_type in eval_modes:
                bmask_thrd = mask_dict[mask_type]['bmask_thrd']

                if mask_type == 'amodal':
                    gt_seg = gt_amodal_segmentation[obj_idx]

                elif mask_type == 'inmodal':
                    gt_seg = gt_inmodal_segmentation[obj_idx]

                elif mask_type == 'occ':
                    gt_seg = (gt_amodal_segmentation[obj_idx] - gt_inmodal_segmentation[obj_idx] > 0).astype(float)

                pred_seg = pred_segmentation[mask_type]
                pred_seg_b = (pred_seg >= bmask_thrd).astype(float)

                iou = np.sum(pred_seg_b * gt_seg) / np.sum((pred_seg_b + gt_seg > 0.5).astype(int))
                mask_dict[mask_type]['iou'].append(iou)
                mask_dict[mask_type]['img_index'].append(ii)
                mask_dict[mask_type]['obj_index'].append(obj_idx)

                if mask_type == 'amodal':
                    disp_iou = disp_iou * disp_counter / (disp_counter + 1) + iou / (disp_counter + 1)
                    disp_counter += 1

            cls_acc.append(pred_acc[obj_idx])
            amodal_bbox_iou.append(calc_iou(pred_box=pred_amodal_bboxes[obj_idx].numpy(), gt_box=gt_amodal_bbox[obj_idx].numpy()))
            amodal_height.append(gt_amodal_bbox[obj_idx][2] - gt_amodal_bbox[obj_idx][0])
            occ.append(gt_occ[obj_idx])

        if ii % 10 == 0:
            print('    {}  -  eval {}/{}     amodal_iou={:.2f}%         '.format(category, ii, N, disp_iou * 100), end='\r')

    cls_acc = np.array(cls_acc)
    amodal_bbox_iou = np.array(amodal_bbox_iou)
    amodal_height = np.array(amodal_height)
    occ = np.array(occ)

    cls_acc_val = np.mean(cls_acc)

    amodal_bbox_iou_val_correct_label = np.mean(amodal_bbox_iou[cls_acc == 1])
    amodal_bbox_iou_val = np.mean(amodal_bbox_iou * cls_acc)

    output = dict()

    print('RPN_iou:', np.mean(RPN_PREDICTION))

    output['cls'] = {'amodal_bbox_iou': amodal_bbox_iou, 'cls_acc': cls_acc, 'amodal_height': amodal_height, 'occ': occ,
                     'cls_acc_val' : cls_acc_val, 'amodal_bbox_iou_val' : amodal_bbox_iou_val, 'amodal_bbox_iou_val_correct_label' : amodal_bbox_iou_val_correct_label, 'num_objects': cls_acc.shape[0]}

    print_line = '{:15}  - {:5} -  cls_acc: {:6.4f}     |     amodal_box_mIoU: {:6.4f}     '.format(category, output['cls']['num_objects'], cls_acc_val, amodal_bbox_iou_val)

    for mask_type in eval_modes:
        m_dict = mask_dict[mask_type]
        iou_perf = np.array(m_dict['iou'])
        iou_perf_cls = iou_perf * cls_acc

        output[mask_type] = {'average iou': np.mean(iou_perf_cls), 'precision': np.mean((iou_perf_cls >= 0.5).astype(float)), 'num_objects': iou_perf.shape[0]}
        print_line += '|     {}_mIoU: {:6.4f}     '.format(mask_type, output[mask_type]['average iou'])

        if demo:
            rank_ind = np.argsort(iou_perf_cls)[::-1]

            out_dir = demo_dir + '{}/'.format(sub_tag)
            if not os.path.exists(out_dir):
                os.mkdir(out_dir)

            i = 0
            for ri in rank_ind:
                if i % 50 == 0 or i < 75:
                    make_demo(data_loader, rank=i, img_index=m_dict['img_index'][ri], obj_index=m_dict['obj_index'][ri], exp_set_up=[mask_type, input_bbox_type, input_gt_label, mask_dict[mask_type]['bmask_thrd']], out_dir=out_dir)
                    print('    {}  -  demo {}/{}     '.format(category, i, iou_perf.shape[0]), end='\r')
                i += 1

    print_(print_line, file=file)

    return output

**Comment by YihongSun** [comment]
Good catch.

Since `eval_performance()` is mostly used in `run_experiment.py`,`sub_tag` is defined in main on [L412](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/run_experiment.py#L412C6-L412C6) and [L470](https://github.com/YihongSun/Bayesian-Amodal/blob/4ce9cbd03c7a5c713eb93c051efffefaa0db2ee5/Code/run_experiment.py#L470).

If you intend to use this function outside of `run_experiment.py` with custom data, then the absence of `sub_tag` would be fine.
