### ISSUE TITLE
What does vector w denote?

### ISSUE THREAD

**Issue by FedericaGielen** [YihongSun/Bayesian-Amodal#8]
What does vector _w_ denote?
![541](https://github.com/YihongSun/Bayesian-Amodal/assets/145773794/fbdf2b56-3bfd-40ce-8a46-505d5b3d17fb)

**Comment by FedericaGielen** [comment]
What is **_b_** IN YOUR PAPER?
![455](https://github.com/YihongSun/Bayesian-Amodal/assets/145773794/b8489fd2-5e9d-43d9-a10e-82a67425a08e)

**Comment by YihongSun** [comment]
- $\vec{w}$ stands for the latent variables { $w_a$ }, which indicate foreground ($w_a=1$) or background ($w_a=0$) for each lattice position $a \in D$. Intuitively, $P(\vec{w} | y, m)$ is the probability of each lattice position $a \in D$ being a foreground pixel given the label $y$ and mixture component $m$, which is further discussed in the ***Shape Modeling*** paragraph.

    - Similarly, $\vec{z}$ stands for the latent variables { $z_a$ }, which indicate visible ($z_a=1$) or occluded ($z_a=0$) for each lattice position $a \in D$.

- $b$ stands for the given bounding box during training. Here, $L_{seg}$ adopts the MIL loss proposed in [16].
